ALTER SESSION SET current_schema = dbsys09;
SELECT Landname FROM LAND;
SELECT * FROM dbsys09.AUSSTATTUNG;
SELECT * FROM dbsys09.BESITZTAUSSTATTUNG;
SELECT * FROM dbsys09.ENTFERNUNG_FW_TA;
SELECT * FROM dbsys09.TOURISTENATTR;
SELECT * FROM dbsys09.BUCHUNG;
SELECT * FROM dbsys09.KUNDE;